# version of docker-compose api
version: "3"

# app is composed of these services
services:
  webapp:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  # host name is identical to container name
  # localhost:27017 -> mongo:27017 (e.g. mongo:27017)
  mongo:
    # container_name: mongogreg
    image: mongo:2.6.11
    ports:
      - "27017:27017"
